### ISSUE TITLE
Tests always reported as failed.

### ISSUE THREAD

**Issue by superafroman** [LambdaTest/wdio-lambdatest-service#2]
The afterTest hook looks for `test.passed` to check for success. This is always `undefined` and so tests are always reported as failed.

The correct function signature is `afterTest(test, context, { error, result, duration, passed, retries })`. Where `passed` is a boolean indicating success.

**Comment by kanhaiya15** [comment]
@superafroman, Thanks for highlighting the issue.
We have checked the issue and this has been resolved. Please connect us if it is still happening
