### ISSUE TITLE
Severity vulnerabilities (dep: request)

### ISSUE THREAD

**Issue by MaximWaveOC** [LambdaTest/wdio-lambdatest-service#58]
Hello team!
Thank you for the great product.
We need your help to solve npm audit.
`
node_modules/request
  @lambdatest/node-rest-client  *
  Depends on vulnerable versions of request
  node_modules/@lambdatest/node-rest-client
    wdio-lambdatest-service  *
    Depends on vulnerable versions of @lambdatest/node-rest-client
    node_modules/wdio-lambdatest-service

3 moderate severity vulnerabilities
`
We use 1.0.16, but it affects 1.0.17 and 2.0.2 too.
Please help to solve it.

Thanks.

**Comment by Shahnawaz-Sk** [comment]
@MaximWaveOC Thank you for opening this issue, we will fix this as soon as possible.

**Comment by Shahnawaz-Sk** [comment]
@MaximWaveOC We have removed the vulnerability from `wdio-lambdatest-service`,  it should continue to work as expected.
Thanks.

**Comment by MaximWaveOC** [comment]
@Shahnawaz-Sk thank you! Where can I find fixed version@1.x.x? Thanks.

**Comment by Shahnawaz-Sk** [comment]
@MaximWaveOC  the new fixed version is `2.0.3`.
Thanks
