### ISSUE TITLE
Can we provide an option for the test config to decide whether to override or not  the session "name" while reporting the results to LambdaTest using rest-api ? 

### ISSUE THREAD

**Issue by vamsidarbhamulla** [LambdaTest/wdio-lambdatest-service#6]
When we try to run 4 parallel sessions from two different capabilities having two test cases each, we are trying to set each test case name appended by the browser capability details in the beforeSession hook and it is being overridden by rest-api call while reporting the test results.

I guess the logic is here: https://github.com/LambdaTest/wdio-lambdatest-service/blob/master/src/service.js#L149 
```c
getBody(failures, calledOnReload = false, browserName) {
        let body = {}
       // I believe this is where the body.name will start getting updated and override any custom config names created by tests
        body.name = this.suiteTitle
        if (browserName) {
            body.name = `${browserName}: ${body.name}`
        }
        if (calledOnReload || this.testCnt) {
            let testCnt = ++this.testCnt
            if (global.browser.isMultiremote) {
                testCnt = Math.ceil(testCnt / global.browser.instances.length)
            }

            body.name += ` (${testCnt})`
        }
        body.status_ind = failures > 0 ? 'failed' : 'passed'
        return body
    }
```
Is there a possibility to accept a boolean option to decide whether it should be updated or not.

**Comment by kanhaiya15** [comment]
Hi @vamsidarbhamulla , your feedback is accepted started working on this, will come with resolution soon.

Stay safe!!

**Comment by kanhaiya15** [comment]
@vamsidarbhamulla , We have published new npm version https://www.npmjs.com/package/wdio-lambdatest-service/v/1.0.2 for this fix, now we updating `testname` from `capability` and if not there then will update from this service. Please try now and let me know your feedback.

Stay safe !!

**Comment by vamsidarbhamulla** [comment]
Thanks @kanhaiya15 . I checked and it is working. I tried an alternative using directly node-tunnel and axios library for rest-api call in the meanwhile. Attaching it for reference in case anyone needs it. 
[lambda.test.conf.js](https://gist.github.com/vamsidarbhamulla/6272f735727c539cb0bb30f38113d548)
