### ISSUE TITLE
Fix GitHub Action workflows

### ISSUE THREAD

**Issue by Delta456** [LambdaTest/wdio-lambdatest-service#89]
GitHub Actions tests workflow fails on all platforms. It must be investigated why they fail and fix the tests so that they pass again.'

Sample fail test report on one of the [commits](https://github.com/LambdaTest/wdio-lambdatest-service/actions/runs/10468492764/job/28989518248)

**Comment by Yash-sudo-web** [comment]
i can work on this issue

**Comment by Delta456** [comment]
@Yash-sudo-web please, go ahead and solve the issue! Thanks :)

**Comment by navin772** [comment]
@calebjubal nope
